<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Application\MCQSystem.Application.csproj" />
    <ProjectReference Include="..\Domain\MCQSystem.Domain.csproj" />
    <ProjectReference Include="..\Persistence\MCQSystem.Persistence.csproj" />
    <ProjectReference Include="..\Infrastructure\MCQSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\MCQSystem.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
